{"version":3,"sources":["../../../../../node_modules/npm/node_modules/asap/asap.js"],"names":["rawAsap","require","freeTasks","module","exports","asap","task","rawTask","length","pop","RawTask","domain","process","prototype","call","enter","threw","exit","requestFlush","push"],"mappings":"AAAA;;AAEA,IAAIA,UAAUC,QAAQ,OAAR,CAAd;AACA,IAAIC,YAAY,EAAhB;;AAEA;;;;;;;;;;AAUAC,OAAOC,OAAP,GAAiBC,IAAjB;AACA,SAASA,IAAT,CAAcC,IAAd,EAAoB;AAChB,QAAIC,OAAJ;AACA,QAAIL,UAAUM,MAAd,EAAsB;AAClBD,kBAAUL,UAAUO,GAAV,EAAV;AACH,KAFD,MAEO;AACHF,kBAAU,IAAIG,OAAJ,EAAV;AACH;AACDH,YAAQD,IAAR,GAAeA,IAAf;AACAC,YAAQI,MAAR,GAAiBC,QAAQD,MAAzB;AACAX,YAAQO,OAAR;AACH;;AAED,SAASG,OAAT,GAAmB;AACf,SAAKJ,IAAL,GAAY,IAAZ;AACA,SAAKK,MAAL,GAAc,IAAd;AACH;;AAEDD,QAAQG,SAAR,CAAkBC,IAAlB,GAAyB,YAAY;AACjC,QAAI,KAAKH,MAAT,EAAiB;AACb,aAAKA,MAAL,CAAYI,KAAZ;AACH;AACD,QAAIC,QAAQ,IAAZ;AACA,QAAI;AACA,aAAKV,IAAL,CAAUQ,IAAV;AACAE,gBAAQ,KAAR;AACA;AACA;AACA,YAAI,KAAKL,MAAT,EAAiB;AACb,iBAAKA,MAAL,CAAYM,IAAZ;AACH;AACJ,KARD,SAQU;AACN;AACA;AACA,YAAID,KAAJ,EAAW;AACP;AACA;AACA;AACA;AACA;AACAhB,oBAAQkB,YAAR;AACH;AACD;AACA;AACA,aAAKZ,IAAL,GAAY,IAAZ;AACA,aAAKK,MAAL,GAAc,IAAd;AACAT,kBAAUiB,IAAV,CAAe,IAAf;AACH;AACJ,CA9BD","file":"asap.js","sourcesContent":["\"use strict\";\n\nvar rawAsap = require(\"./raw\");\nvar freeTasks = [];\n\n/**\n * Calls a task as soon as possible after returning, in its own event, with\n * priority over IO events. An exception thrown in a task can be handled by\n * `process.on(\"uncaughtException\") or `domain.on(\"error\")`, but will otherwise\n * crash the process. If the error is handled, all subsequent tasks will\n * resume.\n *\n * @param {{call}} task A callable object, typically a function that takes no\n * arguments.\n */\nmodule.exports = asap;\nfunction asap(task) {\n    var rawTask;\n    if (freeTasks.length) {\n        rawTask = freeTasks.pop();\n    } else {\n        rawTask = new RawTask();\n    }\n    rawTask.task = task;\n    rawTask.domain = process.domain;\n    rawAsap(rawTask);\n}\n\nfunction RawTask() {\n    this.task = null;\n    this.domain = null;\n}\n\nRawTask.prototype.call = function () {\n    if (this.domain) {\n        this.domain.enter();\n    }\n    var threw = true;\n    try {\n        this.task.call();\n        threw = false;\n        // If the task throws an exception (presumably) Node.js restores the\n        // domain stack for the next event.\n        if (this.domain) {\n            this.domain.exit();\n        }\n    } finally {\n        // We use try/finally and a threw flag to avoid messing up stack traces\n        // when we catch and release errors.\n        if (threw) {\n            // In Node.js, uncaught exceptions are considered fatal errors.\n            // Re-throw them to interrupt flushing!\n            // Ensure that flushing continues if an uncaught exception is\n            // suppressed listening process.on(\"uncaughtException\") or\n            // domain.on(\"error\").\n            rawAsap.requestFlush();\n        }\n        // If the task threw an error, we do not want to exit the domain here.\n        // Exiting the domain would prevent the domain from catching the error.\n        this.task = null;\n        this.domain = null;\n        freeTasks.push(this);\n    }\n};\n\n"]}